export const SocketTypes = {
  SOCKET_INIT: 'SOCKET_INIT',
}

export const AuthTypes = {
  SET_AUTH: 'SET_AUTH',
  SET_USER: 'SET_USER',
  SET_AVATAR: 'SET_AVATAR',
}

export const BasketTypes = {
  SET_BASKET: 'SET_BASKET',
  ADD_BASKET_ITEM: 'ADD_BASKET_ITEM',
  DELETE_BASKET_ITEM: 'DELETE_BASKET_ITEM',
  EDIT_BASKET_ITEM: 'EDIT_BASKET_ITEM',
}

export const ShopTypes = {
  SET_PRODUCT: 'SET_PRODUCT',
  SET_PRODUCTS: 'SET_PRODUCTS',
  CLEAR_PRODUCTS: 'CLEAR_PRODUCTS',
  SET_FILTER: 'SET_FILTER',
  SET_TOTAL_COUNT: 'SET_TOTAL_COUNT',
  SET_SKIP_PRODUCTS: 'SET_SKIP_PRODUCTS',
  SET_TYPES: 'SET_TYPES',
  SET_BRANDS: 'SET_BRANDS',
}

export const AdminTypes = {
  SET_ADMIN_PRODUCTS: 'SET_ADMIN_PRODUCTS',
  SET_ADMIN_PRODUCT: 'SET_ADMIN_PRODUCT',
  DELETE_ADMIN_PRODUCT: 'DELETE_ADMIN_PRODUCT',
  EDIT_ADMIN_PRODUCT: 'EDIT_ADMIN_PRODUCT',
  SET_TOTAL_ADMIN_PRODUCTS_COUNT: 'SET_TOTAL_ADMIN_PRODUCTS_COUNT',
  SET_SKIP_ADMIN_PRODUCTS: 'SET_SKIP_ADMIN_PRODUCTS',

  SET_ADMIN_USERS: 'SET_ADMIN_USERS',
  SET_ADMIN_USER: 'SET_ADMIN_USER',
  DELETE_ADMIN_USER: 'DELETE_ADMIN_USER',
  EDIT_ADMIN_USER: 'EDIT_ADMIN_USER',
  SET_TOTAL_ADMIN_USERS_COUNT: 'SET_TOTAL_ADMIN_USERS_COUNT',
  SET_SKIP_ADMIN_USERS: 'SET_SKIP_ADMIN_USERS',

  SET_ADMIN_TYPES: 'SET_ADMIN_TYPES',
  SET_ADMIN_TYPE: 'SET_ADMIN_TYPE',
  DELETE_ADMIN_TYPE: 'DELETE_ADMIN_TYPE',
  EDIT_ADMIN_TYPE: 'EDIT_ADMIN_TYPE',

  SET_ADMIN_BRANDS: 'SET_ADMIN_BRANDS',
  SET_ADMIN_BRAND: 'SET_ADMIN_BRAND',
  DELETE_ADMIN_BRAND: 'DELETE_ADMIN_BRAND',
  EDIT_ADMIN_BRAND: 'EDIT_ADMIN_BRAND',
}

export const NavbarTypes = {
  SHOW_NAVBAR: 'SHOW_NAVBAR',
  SWIPE_NAVBAR: 'SWIPE_NAVBAR',
}
